DEFAULT_S3_BUCKET = "cinerag-data"
S3_RAW_DATA_FOLDER = "raw/"
S3_PROCESSED_DATA_FOLDER = "processed/"
S3_EMBEDDINGS_FOLDER = "embeddings/"
DEFAULT_FILE_NAME = "movie_data"

EMBEDDING_BATCH_SIZE = 128
VECTOR_COLLECTION_NAME = "cinerag_stage"

QDRANT_HOST = "localhost"
QDRANT_PORT = 6333